---
- set_fact: userno={{ item }}

- name: Get 3scale master hostname
  # shell: "oc get route/system-master -n 3scale -o json | jq -r '.spec.host'" # for 3scale 2.5
  shell: "oc get route -n {{ threescale_namespace }} -l zync.3scale.net/route-to=system-master -o jsonpath='{.items[0].spec.host}'" # for 3scale 2.6
  register: threescale_host_cmd

- name: Set 3scale master hostname var
  set_fact:
    threescale_host: "{{ threescale_host_cmd.stdout }}"

- debug:
    msg: 3scale master URL is {{ threescale_host }}

- name: Retrieve 3scale master access token
  shell: oc describe dc/system-app -n {{ threescale_namespace }} | grep MASTER_ACCESS_TOKEN | head -1 | awk -F '"' '{print $2}'
  register: master_access_token_cmd

- set_fact:
    threescale_master_access_token: "{{ master_access_token_cmd.stdout }}"

- debug:
    msg: 3scale master access token is {{ threescale_master_access_token }}

- name: Wait until 3scale API is available 
  uri: 
    url: https://{{ threescale_host }}
    method: HEAD
    validate_certs: no
  register: wait_threescale_result
  until: wait_threescale_result is succeeded
  ignore_errors: yes
  retries: 10
  delay: 60

- name: Create Tenant {{ item }}
  uri:
    url: https://{{ threescale_host }}/master/api/providers.xml
    method: POST
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "access_token={{threescale_master_access_token}}&org_name={{ userno }}&username={{ userno }}&email={{ userno }}%40example.com&password={{ threescale_tenant_admin_password }}"
    validate_certs: no
    status_code: 201,409
  register: create_tenant_result
  retries: 3
  delay: 10
  until: create_tenant_result is not failed

- debug: var=create_tenant_result.content

- set_fact: signup={{ create_tenant_result.content }}

- name: Get Ids
  xml:
    xmlstring: '{{ signup }}'
    xpath: //account/id | //user[username='{{ userno }}']/id | //account/admin_domain | //account/domain
    content: text
  register: xmlstring

- debug: var=xmlstring.matches

- set_fact: ids={{ xmlstring.matches }}

- name: Activate Tenant User {{ item }}
  uri:
    url: https://{{ threescale_host }}/admin/api/accounts/{{ ids[0].id }}/users/{{ ids[3].id }}/activate.xml
    method: PUT
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "access_token={{threescale_master_access_token}}&account_id={{ ids[0].id }}&id={{ ids[3].id }}"
    validate_certs: no
    status_code: 200
  register: activate_tenant_result
  retries: 3
  delay: 10
  until: activate_tenant_result is not failed
